sudo: required

services:
  - docker

before_install:
  - docker build -t au9ustine/hirilonde -f Dockerfile.haproxy .

script: true

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push au9ustine/hirilonde:latest
  
